Calculate chol_psd using testout_3.1.csv and testout_4.1.csv

In [10]:
import pandas as pd
import numpy as np

In [11]:
# read input data
data = pd.read_csv('../testfiles/data/testout_3.1.csv')
data

         x1        x2        x3        x4        x5
0  1.173986 -0.617989 -0.284559 -0.065152 -0.688287
1 -0.617989  1.318197  0.017092  0.445696  0.139176
2 -0.284559  0.017092  0.918102  0.354147  0.246056
3 -0.065152  0.445696  0.354147  0.894764 -0.218717
4 -0.688287  0.139176  0.246056 -0.218717  0.522607

In [12]:
L = np.linalg.cholesky(data)
pd.DataFrame(L)

          0         1         2         3             4
0  1.083506  0.000000  0.000000  0.000000  0.000000e+00
1 -0.570360  0.996437  0.000000  0.000000  0.000000e+00
2 -0.262628 -0.133175  0.911807  0.000000  0.000000e+00
3 -0.060130  0.412871  0.431384  0.731160  0.000000e+00
4 -0.635240 -0.223938  0.054179 -0.256892  1.053671e-08