In [1]:
import pandas as pd
import numpy as np

#### 6.1
calculate arithmetic returns using test6.csv and testout6.1.csv

In [2]:
# read input data
data = pd.read_csv('../testfiles/data/test6.csv')

data["Date"] = pd.to_datetime(data["Date"])
data = data.sort_values("Date")
data = data.set_index("Date")

data

,SPY,AAPL,MSFT,AMZN,NVDA,GOOGL,TSLA,GOOG,BRK-B,META,...,CI,ETN,SLB,PGR,SCHW,LRCX,ZTS,C,BSX,AMT
Date,,,,,,,,,,,,,,,,,,,,,
2022-09-01,388.679565,157.028442,257.908386,127.820000,139.243423,109.739998,277.160004,110.550003,282.429993,165.360001,...,282.124664,136.138718,36.036259,123.325203,70.653595,424.766022,158.011505,46.662727,40.990002,249.972107
2022-09-02,384.581177,154.891113,253.609909,127.510002,136.346054,107.849998,270.209991,108.680000,277.670013,160.320007,...,281.791626,134.696564,37.229321,122.039116,69.294113,422.966797,155.602798,46.748875,40.490002,243.384186
2022-09-06,383.130066,153.618668,250.826813,126.110001,134.527710,106.809998,274.420013,107.480003,276.589996,158.539993,...,280.483856,135.834595,36.703716,122.108894,69.422180,419.574921,155.464035,46.155418,40.380001,246.615067
2022-09-07,390.013000,155.040237,255.620483,129.479996,137.056152,109.449997,283.700012,110.480003,281.040009,160.389999,...,285.154480,138.591293,36.408989,126.814598,70.722557,424.726715,158.992813,46.547867,41.470001,251.776749
2022-09-08,392.562256,153.549088,256.046387,129.820007,139.814484,108.379997,289.260010,109.419998,283.339996,162.059998,...,285.852631,140.523956,37.499485,128.828476,72.072182,431.766174,157.099579,47.763493,42.709999,253.882172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-18,443.630005,177.970001,329.059998,139.979996,439.660004,138.210007,265.279999,138.960007,370.429993,302.549988,...,285.339996,219.149994,61.209999,140.559998,57.860001,635.650024,179.649994,42.639999,53.000000,179.529999
2023-09-19,442.709991,179.070007,328.649994,137.630005,435.200012,138.039993,266.500000,138.830002,370.480011,305.070007,...,284.640015,216.160004,60.430000,142.470001,57.730000,625.150024,181.979996,42.680000,53.029999,177.360001
2023-09-20,438.640015,175.490005,320.769989,135.289993,422.390015,133.740005,262.589996,134.589996,366.820007,299.670013,...,287.329987,214.649994,59.790001,142.690002,56.669998,618.859985,181.479996,42.299999,54.099998,177.410004
2023-09-21,431.390015,173.929993,319.529999,129.330002,410.170013,130.440002,255.699997,131.360001,363.279999,295.730011,...,290.839996,210.649994,58.820000,142.399994,56.009998,610.390015,176.630005,41.709999,53.970001,169.320007
2023-09-22,430.420013,174.789993,317.010010,129.119995,416.100006,130.250000,244.880005,131.250000,360.160004,299.079987,...,289.440002,212.660004,59.040001,143.259995,55.150002,619.109985,176.679993,40.919998,53.599998,166.210007

In [3]:
# arithmetic return
returns = data.pct_change()
returns = returns.dropna()
returns

,SPY,AAPL,MSFT,AMZN,NVDA,GOOGL,TSLA,GOOG,BRK-B,META,...,CI,ETN,SLB,PGR,SCHW,LRCX,ZTS,C,BSX,AMT
Date,,,,,,,,,,,,,,,,,,,,,
2022-09-02,-0.010544,-0.013611,-0.016667,-0.002425,-0.020808,-0.017223,-0.025076,-0.016915,-0.016854,-0.030479,...,-0.001180,-0.010593,0.033107,-0.010428,-0.019242,-0.004236,-0.015244,0.001846,-0.012198,-0.026355
2022-09-06,-0.003773,-0.008215,-0.010974,-0.010980,-0.013336,-0.009643,0.015581,-0.011042,-0.003890,-0.011103,...,-0.004641,0.008449,-0.014118,0.000572,0.001848,-0.008019,-0.000892,-0.012695,-0.002717,0.013275
2022-09-07,0.017965,0.009254,0.019111,0.026723,0.018795,0.024717,0.033817,0.027912,0.016089,0.011669,...,0.016652,0.020295,-0.008030,0.038537,0.018731,0.012279,0.022698,0.008503,0.026994,0.020930
2022-09-08,0.006536,-0.009618,0.001666,0.002626,0.020126,-0.009776,0.019598,-0.009595,0.008184,0.010412,...,0.002448,0.013945,0.029951,0.015880,0.019083,0.016574,-0.011908,0.026116,0.029901,0.008362
2022-09-09,0.015535,0.018840,0.022977,0.026575,0.028377,0.020945,0.036023,0.021568,0.008576,0.043749,...,0.007327,0.017244,0.038774,-0.004179,0.018863,0.026460,0.036721,0.015431,0.005385,-0.000306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-18,0.000586,0.016913,-0.003513,-0.002920,0.001503,0.005895,-0.033201,0.004772,0.006986,0.007459,...,0.007485,0.006938,0.010399,0.013118,-0.006183,0.020125,-0.003329,-0.001639,0.001890,-0.003386
2023-09-19,-0.002074,0.006181,-0.001246,-0.016788,-0.010144,-0.001230,0.004599,-0.000936,0.000135,0.008329,...,-0.002453,-0.013644,-0.012743,0.013589,-0.002247,-0.016519,0.012970,0.000938,0.000566,-0.012087
2023-09-20,-0.009193,-0.019992,-0.023977,-0.017002,-0.029435,-0.031150,-0.014672,-0.030541,-0.009879,-0.017701,...,0.009450,-0.006986,-0.010591,0.001544,-0.018361,-0.010062,-0.002748,-0.008903,0.020177,0.000282
2023-09-21,-0.016528,-0.008889,-0.003866,-0.044053,-0.028931,-0.024675,-0.026239,-0.023999,-0.009651,-0.013148,...,0.012216,-0.018635,-0.016223,-0.002032,-0.011646,-0.013686,-0.026725,-0.013948,-0.002403,-0.045601
2023-09-22,-0.002249,0.004945,-0.007887,-0.001624,0.014457,-0.001457,-0.042315,-0.000837,-0.008588,0.011328,...,-0.004814,0.009542,0.003740,0.006039,-0.015354,0.014286,0.000283,-0.018940,-0.006856,-0.018368

#### 1.2
Calculate log returns, using test6.csv and testout6.2.csv

In [4]:
log_returns = np.log(data).diff()
log_returns = log_returns.dropna()
log_returns

,SPY,AAPL,MSFT,AMZN,NVDA,GOOGL,TSLA,GOOG,BRK-B,META,...,CI,ETN,SLB,PGR,SCHW,LRCX,ZTS,C,BSX,AMT
Date,,,,,,,,,,,,,,,,,,,,,
2022-09-02,-0.010600,-0.013705,-0.016807,-0.002428,-0.021027,-0.017373,-0.025396,-0.017060,-0.016997,-0.030953,...,-0.001181,-0.010650,0.032571,-0.010483,-0.019429,-0.004245,-0.015361,0.001844,-0.012273,-0.026708
2022-09-06,-0.003780,-0.008249,-0.011035,-0.011040,-0.013426,-0.009690,0.015460,-0.011103,-0.003897,-0.011165,...,-0.004652,0.008413,-0.014219,0.000572,0.001846,-0.008052,-0.000892,-0.012776,-0.002720,0.013187
2022-09-07,0.017806,0.009211,0.018931,0.026372,0.018621,0.024416,0.033258,0.027530,0.015961,0.011601,...,0.016515,0.020091,-0.008062,0.037813,0.018558,0.012204,0.022445,0.008467,0.026636,0.020714
2022-09-08,0.006515,-0.009664,0.001665,0.002623,0.019926,-0.009824,0.019409,-0.009641,0.008151,0.010358,...,0.002445,0.013849,0.029512,0.015756,0.018904,0.016438,-0.011979,0.025780,0.029463,0.008327
2022-09-09,0.015416,0.018664,0.022717,0.026228,0.027982,0.020729,0.035389,0.021339,0.008540,0.042819,...,0.007300,0.017097,0.038041,-0.004188,0.018687,0.026116,0.036063,0.015313,0.005371,-0.000306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-18,0.000586,0.016772,-0.003519,-0.002925,0.001502,0.005878,-0.033765,0.004761,0.006962,0.007431,...,0.007457,0.006914,0.010346,0.013033,-0.006203,0.019925,-0.003334,-0.001640,0.001889,-0.003392
2023-09-19,-0.002076,0.006162,-0.001247,-0.016931,-0.010196,-0.001231,0.004588,-0.000936,0.000135,0.008295,...,-0.002456,-0.013738,-0.012825,0.013497,-0.002249,-0.016656,0.012886,0.000938,0.000566,-0.012161
2023-09-20,-0.009236,-0.020195,-0.024269,-0.017148,-0.029877,-0.031646,-0.014780,-0.031017,-0.009928,-0.017859,...,0.009406,-0.007010,-0.010647,0.001543,-0.018532,-0.010113,-0.002751,-0.008943,0.019976,0.000282
2023-09-21,-0.016666,-0.008929,-0.003873,-0.045053,-0.029357,-0.024984,-0.026589,-0.024291,-0.009697,-0.013235,...,0.012142,-0.018811,-0.016357,-0.002035,-0.011715,-0.013781,-0.027088,-0.014046,-0.002406,-0.046673
2023-09-22,-0.002251,0.004932,-0.007918,-0.001625,0.014354,-0.001458,-0.043237,-0.000838,-0.008625,0.011264,...,-0.004825,0.009497,0.003733,0.006021,-0.015473,0.014185,0.000283,-0.019122,-0.006879,-0.018538